[code] Change error message (DAP might be disabled)
When the JTAG reset routine for the netx 90 cannot detect the chip type,
mention that it may be because the DAP is disabled.

Error: Could not detect the chip type.
The debug access port might be disabled.